# Generated by Django 5.1.1 on 2024-10-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created')], default='created', max_length=255),
        ),
    ]
