# Generated by Django 5.1.1 on 2024-10-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_status_alter_order_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PAID', 'Paid'), ('BAKING', 'Baking'), ('DELIVERING', 'Delivering'), ('DELIVERED', 'Delivered')], default='created', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
