# Generated by Django 5.1.1 on 2024-10-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_code',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
