# Generated by Django 5.1.1 on 2024-10-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_address_order_delivery_order_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PAID', 'Paid'), ('BAKING', 'Baking'), ('READY FOR PICK UP', 'Ready for pick up'), ('DELIVERING', 'Delivering'), ('DELIVERED', 'Delivered')], default='created', max_length=255),
        ),
    ]
