# Generated by Django 5.1.1 on 2024-10-14 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='paid',
        ),
    ]
