# Generated by Django 5.1.1 on 2024-10-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_available', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='product/pizza')),
                ('small_price', models.DecimalField(decimal_places=2, default=7.99, max_digits=7)),
                ('medium_price', models.DecimalField(decimal_places=2, default=10.99, max_digits=7)),
                ('large_price', models.DecimalField(decimal_places=2, default=15.99, max_digits=7)),
                ('ingredients', models.ManyToManyField(related_name='pizzas', to='product.ingredient')),
                ('other_ingredients', models.ManyToManyField(blank=True, to='product.ingredient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
