# Generated by Django 5.1.1 on 2024-09-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('DOUGH', 'Dough'), ('SAUCE', 'Sauce'), ('CHEESE', 'Cheese'), ('MEAT', 'Meat'), ('VEGETABLE', 'Vegetable'), ('HERB_SPICE', 'Herb & Spice'), ('SPECIAL', 'Special'), ('ADD_ON', 'Add-On')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='pizza')),
                ('small_price', models.DecimalField(decimal_places=2, default=7.99, max_digits=7)),
                ('medium_price', models.DecimalField(decimal_places=2, default=10.99, max_digits=7)),
                ('large_price', models.DecimalField(decimal_places=2, default=15.99, max_digits=7)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('ingredients', models.ManyToManyField(related_name='pizzas', to='pizza.ingredient')),
            ],
        ),
    ]
