# Generated by Django 5.1.1 on 2024-10-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('DOUGH', 'Dough'), ('SAUCE', 'Sauce'), ('CHEESE', 'Cheese'), ('MEAT', 'Meat'), ('VEGETABLE', 'Vegetable'), ('HERB_SPICE', 'Herb & Spice'), ('SPECIAL', 'Special'), ('ADD ON', 'Add on')], max_length=100)),
                ('edit_type', models.CharField(blank=True, choices=[('ADD', 'Add'), ('CHANGE', 'Change')], max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
