# Generated by Django 5.1.1 on 2024-09-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
